on:
  pull_request:
    branches: [ dev ]
    
name: Yarn CI
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
      - run: echo $DATABASE_ENV
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build