name: Build

on:
  pull_request:
    branches: [dev]

jobs:
  build:
    env:
      DATABASE_URL: ${{secrets.DATABASE_URL}}
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: nodeModulesCache
        name: Caching node modules
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: borales/actions-yarn@v2.0.0
        name: Installing dependencies
        with:
          cmd: install
        if: steps.nodeModulesCache.outputs.cache-hit != 'true'
      - uses: actions/cache@v2
        name: Caching next
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}
      - uses: borales/actions-yarn@v2.0.0
        name: Building Next
        with:
          cmd: build
